### ISSUE TITLE
Problem when halving Retina sprites

### ISSUE THREAD

**Issue by stagas** [Ensighten/spritesmith#56]
There's a problem when compiling sprites for low-dpi and Retina targets, in that the `background-size` trick to fit the Retina sprites on the designs, needs to be exactly half. But in cases that the Retina version is not in even dimensions, it results in half pixels, which has problems rendering and positioning in browsers.

The [workaround](https://github.com/stagas/spritesmith/commit/fc396d9bb3aa4edb0abd08f6cad2733ba5fe99f3) I worked on is to conditionally add padding to sprites so they are always even sized, and the result image can be halved without that issue mentioned above.

I didn't do a pull because this probably breaks everything and it should most likely be an option, or something. What do you think?

**Comment by twolfson** [comment]
We don't want this as a setting in `spritesmith` as there are non-retina spritesheets that can have odd pixel widths. In `grunt-spritesmith`/`gulp.spritesmith`, when generating retina spritesheets we prefer to point out the error to developers as it highlights that there could be a deeper problem due to improperly matching sizes of sprites.

https://github.com/twolfson/gulp.spritesmith/pull/39

https://github.com/twolfson/gulp.spritesmith/issues/41
